env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
  amd: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  eol-last:
    - error
    - always
  max-params:
    - error
    - 3
  complexity:
    - error
    - 13
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 0
      maxBOF: 0
  no-nested-ternary:
    - error
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
  one-var-declaration-per-line:
    - error
    - initializations
  operator-linebreak:
    - error
    - after
  padded-blocks:
    - error
    - blocks: never
      classes: always
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-unary-ops:
    - error
  spaced-comment:
    - error
  space-infix-ops:
    - error
  keyword-spacing:
    - error
    - after: true
  space-before-blocks:
    - error

globals:
    fabric: true
    requirejs: true
    assert: true

# TODO: пройтись по http://eslint.org/docs/rules/
